---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra2-config-pvc
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: raspberrypi-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
