---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: infra
  labels:
    app: nginx-ingress
  annotations:
    strategy.spinnaker.io/versioned: "false"
data:
  enable-vts-status: "true"
  gzip-types: "application/atom+xml application/javascript application/x-javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component application/x-eml"
  log-format-escape-json: "true"
  log-format-upstream: '{
    "time": "$time_iso8601",
    "ip_address": "$remote_addr",
    "http_user_agent":"$http_user_agent",
    "status": "$status",
    "upstream_status": "$upstream_status",
    "request_method": "$request_method",
    "content_type": "$content_type",
    "https": "$https",
    "hostname": "$hostname",
    "x_forward_for": "$proxy_add_x_forwarded_for",
    "path_original": "$request_uri",
    "path_normalized": "$uri",
    "request_line": "$request",
    "request_body": "$request_body",
    "request_length": "$request_length",
    "request_id": "$request_id",
    "request_time": "$request_time",
    "bytes_sent": "$bytes_sent",
    "server_protocol": "$server_protocol",
    "host": "$http_host",
    "basic_auth_username": "$remote_user",
    "client_ip": "$remote_addr",
    "request_protocol": "$scheme",
    "response_headers_content_type": "$sent_http_content_type",
    "nginx_version": "$nginx_version",
    "tls_cipher": "$ssl_cipher",
    "tls_sni": "$ssl_server_name",
    "tls_protocol": "$ssl_protocol"
  }'
  use-gzip: "true"
#  error-log-level: "info"
