---
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  namespace: infra
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: nginx-ingress

